name: Build and Release Anki Deck

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate Anki deck
        run: python generate_anki_deck.py
      
      - name: Generate release date
        id: date
        run: echo "release_date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Toki Pona Anki Deck ${{ steps.date.outputs.release_date }}
          tag_name: v${{ steps.date.outputs.release_date }}
          body: |
            Automatically generated Toki Pona Anki Deck with Sitelen Pona
            
            Generated on ${{ steps.date.outputs.release_date }}
          files: toki_pona_sitelen_pona.apkg
          draft: false
          prerelease: false